version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  message-broker:
    build:
      context: .
      dockerfile: ./message-broker/Dockerfile
    image: guardian-message-broker
    ports:
      - 3003:3003
    expose:
      - 7500
  ui-service:
    build:
      context: .
      dockerfile: ./ui-service/Dockerfile
    image: guardian-ui-service
    ports:
      - 3002:3002
    depends_on:
      - mongo
      - message-broker
      - guardian-service
  guardian-service:
    build:
      context: .
      dockerfile: ./guardian-service/Dockerfile
    image: guardian-service
    #    ports:
    #      - 3004:3004
    depends_on:
      - mongo
      - message-broker
  mrv-sender:
    build:
      context: .
      dockerfile: ./mrv-sender/Dockerfile
    image: guardian-mrv-sender
    ports:
      - 3005:3005
  tymlez-service:
    build:
      context: .
      dockerfile: ./tymlez-service/Dockerfile
    image: guardian-tymlez-service
    ports:
      - 3010:3010
    depends_on:
      - mongo
      - message-broker
volumes:
  mongo:
  # volume-guardian-service:
  # volume-ui-service:
  # volume-mrv-sender:
#  volume-message-broker:
